In [1]:
import pandas as pd

In [2]:
path="./hate_crime/hate_crime.csv"

In [5]:
US_crime=pd.read_csv(path)

/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (19) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
US_crime.head()

,INCIDENT_ID,DATA_YEAR,ORI,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_TYPE_NAME,STATE_ABBR,STATE_NAME,DIVISION_NAME,REGION_NAME,...,OFFENDER_RACE,OFFENDER_ETHNICITY,VICTIM_COUNT,OFFENSE_NAME,TOTAL_INDIVIDUAL_VICTIMS,LOCATION_NAME,BIAS_DESC,VICTIM_TYPES,MULTIPLE_OFFENSE,MULTIPLE_BIAS
0,3015,1991,AR0040200,Rogers,NaN,City,AR,Arkansas,West South Central,South,...,White,NaN,1,Intimidation,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-Black or African American,Individual,S,S
1,3016,1991,AR0290100,Hope,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,1,Simple Assault,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-White,Individual,S,S
2,43,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,1,Aggravated Assault,1.0,Residence/Home,Anti-Black or African American,Individual,S,S
3,44,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,2,Aggravated Assault;Destruction/Damage/Vandalis...,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-White,Individual,M,S
4,3017,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,NaN,1,Aggravated Assault,1.0,Service/Gas Station,Anti-White,Individual,S,S

In [7]:
US_crime=US_crime[["DATA_YEAR","STATE_NAME","OFFENDER_RACE","OFFENSE_NAME","LOCATION_NAME","BIAS_DESC"]].copy()

In [14]:
Texas_crime=US_crime[US_crime['STATE_NAME']=='Texas']
Texas_crime.head()

,DATA_YEAR,STATE_NAME,OFFENDER_RACE,OFFENSE_NAME,LOCATION_NAME,BIAS_DESC
4203,1991,Texas,White,Simple Assault,Jail/Prison/Penitentiary/Corrections Facility,Anti-Black or African American
4204,1991,Texas,White,Aggravated Assault,Parking/Drop Lot/Garage,Anti-Black or African American
4205,1991,Texas,White,Intimidation,Convenience Store,Anti-Arab
4206,1991,Texas,Black or African American,Aggravated Assault,Other/Unknown,Anti-White
4207,1991,Texas,Unknown,Destruction/Damage/Vandalism of Property,Residence/Home,Anti-Black or African American

In [17]:
path2="Hate_Crimes_2018_Final.csv"
Austin_crime=pd.read_csv(path2)
Austin_crime.head(10)

,Month,Incident Number,Date of Incident/Day of Week,Number of vitims under 18,Number of Victims Over 18,Number of Offenders under 18,Number of Offenders over 18,Race/Ethnic of Offender(s),Offense(s),Offense Location,Bias,Victim Type
0,January,2018-251458,01 25 2018/Thur,0,2,0,1,White/NotHispanic,Burglary/Assault,Residence/Home,Anti-Lesbian,Individual
1,January,2018-200595,01 19 2018/Fri,0,0,0,0,Unknown,Vandalism,Parking Lot/Garage,Anti-Black,Vehicle
2,February,2018-400447,02 08 2018/Thur,0,1,0,1,White/NotHispanic,Assault,Parking Lot/Garage,Anti-Gay,Individual
3,February,2018-530804,02 22 2018/Thur,0,1,0,1,White/NotHispanic,Vandalism,Highway/Road/Street,Anti-Black,Individual
4,March,2018-611809,03 02 2018/Fri,0,1,0,4,Black/Unknown,Assault,Highway/Road/Street,Anti-Hispanic,Individual
5,March,2018-651279,03 06 2018/Tue,0,0,1,1,White/NotHispanic,Vandalism,Convenience Store,Anti-Arab,Business
6,March,2018-670117,03 08 2018/Thur,0,1,0,1,White/NotHispanic,Assault,Highway/Road/Street,Anti-Black,Individual
7,April,2018-911582,04 01 2018/Sun,0,1,0,1,White/NotHispanic,Intimidation,Parking Lot/Garage,Anti-Black,Individual
8,April,2018-120696,04 30 2018/Mon,0,1,0,1,White/Hispanic,Assault,Streets/Highway/Road/Alley,Anti-White,Individual
9,May,2018-1410057,05 21 2018/Mon,0,1,0,1,White/Hispanic,Assault,Bar/Nightclub,Anti-Gay,Individual

,Incident Number,Highest Offense Description,Highest Offense Code,Family Violence,Occurred Date Time,Occurred Date,Occurred Time,Report Date Time,Report Date,Report Time,...,Census Tract,Clearance Status,Clearance Date,UCR Category,Category Description,X-coordinate,Y-coordinate,Latitude,Longitude,Location
0,201811117,ROBBERY BY ASSAULT,303,N,01/01/2018 11:48:00 AM,01/01/2018,1148,01/01/2018 11:48:00 AM,01/01/2018,1148,...,18.12,N,04/05/2018,120,Robbery,3129103.0,3129103.0,30.326957,-97.694334,"(30.32695651, -97.69433415)"
1,201810248,CRIMINAL TRESPASS/HOTEL,2722,N,01/01/2018 04:41:00 AM,01/01/2018,441,01/01/2018 04:41:00 AM,01/01/2018,441,...,23.00,N,01/02/2018,NaN,NaN,3114042.0,3114042.0,30.226253,-97.744786,"(30.22625287, -97.74478642)"
2,201811933,ASSAULT W/INJURY-FAM/DATE VIOL,900,Y,01/01/2018 11:16:00 PM,01/01/2018,2316,01/01/2018 11:16:00 PM,01/01/2018,2316,...,24.19,N,01/10/2018,NaN,NaN,3109221.0,3109221.0,30.197544,-97.760820,"(30.19754361, -97.7608199)"
3,20185000028,BURGLARY OF VEHICLE,601,N,12/31/2017 11:30:00 PM,12/31/2017,2330,01/01/2018 10:46:00 AM,01/01/2018,1046,...,11.00,N,01/02/2018,23F,Theft,3116012.0,3116012.0,30.265534,-97.737491,"(30.26553403, -97.73749138)"
4,201810183,DOC DISCHARGE GUN - PUB PLACE,2408,N,01/01/2018 01:20:00 AM,01/01/2018,120,01/01/2018 01:20:00 AM,01/01/2018,120,...,23.16,N,01/05/2018,NaN,NaN,3118741.0,3118741.0,30.239899,-97.729536,"(30.23989895, -97.72953607)"